version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your workflow files
    schedule:
      interval: "weekly" # Change to "daily" if you want more frequent checks
      time: "10:00" # (Optional) Runs at 4 AM UTC
      day: saturday # (Optional) Runs every Monday
    open-pull-requests-limit: 5
